# Any of these config options can or can not be provided in the .toml file
# Feel free to place this file in your home directory, i.e: cp examples/.explainer-config.toml ~
# Note: for the tool to work, you must provide the apiKey in either the .toml/.env files, or via the command line

apiKey = "YOUR_API_KEY"
baseURL = "https://api.groq.com/"
temperature = 0.8 # between 0.1 and 2
model = "llama-3.1-70b-versatile" # any supported model
output = "testingToml.txt" # will overwrite a file with the same name
tokenUsage = false # can be true or false